// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package cart

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CartServiceClient is the client API for CartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartServiceClient interface {
	InsertCart(ctx context.Context, in *CartInsertRequest, opts ...grpc.CallOption) (*CartInsertResponse, error)
	DetailCart(ctx context.Context, in *CartDetailRequest, opts ...grpc.CallOption) (*CartDetailResponse, error)
}

type cartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCartServiceClient(cc grpc.ClientConnInterface) CartServiceClient {
	return &cartServiceClient{cc}
}

func (c *cartServiceClient) InsertCart(ctx context.Context, in *CartInsertRequest, opts ...grpc.CallOption) (*CartInsertResponse, error) {
	out := new(CartInsertResponse)
	err := c.cc.Invoke(ctx, "/proto.CartService/InsertCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartServiceClient) DetailCart(ctx context.Context, in *CartDetailRequest, opts ...grpc.CallOption) (*CartDetailResponse, error) {
	out := new(CartDetailResponse)
	err := c.cc.Invoke(ctx, "/proto.CartService/DetailCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartServiceServer is the server API for CartService service.
// All implementations must embed UnimplementedCartServiceServer
// for forward compatibility
type CartServiceServer interface {
	InsertCart(context.Context, *CartInsertRequest) (*CartInsertResponse, error)
	DetailCart(context.Context, *CartDetailRequest) (*CartDetailResponse, error)
	mustEmbedUnimplementedCartServiceServer()
}

// UnimplementedCartServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCartServiceServer struct {
}

func (UnimplementedCartServiceServer) InsertCart(context.Context, *CartInsertRequest) (*CartInsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertCart not implemented")
}
func (UnimplementedCartServiceServer) DetailCart(context.Context, *CartDetailRequest) (*CartDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetailCart not implemented")
}
func (UnimplementedCartServiceServer) mustEmbedUnimplementedCartServiceServer() {}

// UnsafeCartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartServiceServer will
// result in compilation errors.
type UnsafeCartServiceServer interface {
	mustEmbedUnimplementedCartServiceServer()
}

func RegisterCartServiceServer(s grpc.ServiceRegistrar, srv CartServiceServer) {
	s.RegisterService(&CartService_ServiceDesc, srv)
}

func _CartService_InsertCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartInsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).InsertCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CartService/InsertCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).InsertCart(ctx, req.(*CartInsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartService_DetailCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServiceServer).DetailCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CartService/DetailCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServiceServer).DetailCart(ctx, req.(*CartDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CartService_ServiceDesc is the grpc.ServiceDesc for CartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CartService",
	HandlerType: (*CartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertCart",
			Handler:    _CartService_InsertCart_Handler,
		},
		{
			MethodName: "DetailCart",
			Handler:    _CartService_DetailCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart/cart.proto",
}
